# Generated by Django 5.1rc1 on 2024-08-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auction_start_time_auction_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
