# Generated by Django 5.1rc1 on 2024-08-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auction_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='is_active',
        ),
    ]
