# Generated by Django 5.1rc1 on 2024-08-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_auction_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_true',
            field=models.BooleanField(default=False),
        ),
    ]
